### ISSUE TITLE
'npm run format' not working

### ISSUE THREAD

**Issue by ZsakaiBalint** [ZsakaiBalint/integration-node-library#12]
`npm run format` to format all source files with `prettier` is partially working:
    - The format script in package.js was adapted for .ts files
    - `index.ts` file project file is missing!
    - Checked-in files were not formatted. Running `npm run format` changed 24 files
    - Note: GitHub actions in forked repository are not active. This would have generated a build error at code check-in.

**Comment by ZsakaiBalint** [comment]
The cause of the error was that we only need to format source code files, which are all TypeScript files. The previous npm script formatted the compiled files in the /dist folder too (JavaScript), which causes bugs. See [this blog post](https://khalilstemmler.com/blogs/typescript/eslint-for-typescript/).

**Comment by zehnm** [comment]
At least the `dist` directory should be added to the ignored directory configuration (`node_modules` is excluded by default according to the docs). In the past this was done with `.eslintignore`.

It seems that eslint has changed the configuration files / format ([eslintrc is listed as deprectated](https://eslint.org/docs/latest/use/configure/configuration-files-deprecated)):
https://eslint.org/docs/latest/use/configure/ignore

However, in the cli documentation the .eslintignore is still mentioned: https://eslint.org/docs/latest/use/command-line-interface

Please check which configuration should be used with the current eslint version. Then add the `dist`directory to the ignore list.

Further improvement: specifying the include files / directories should also be done in the configuration file, if that's still required after defining the ignore setting.

Reason: the fewer command line parameters in the `scripts` block of `package.json`, the better :-)
This allows anyone just to run eslint, without having to search for additional configuration options. Also IDEs should work better with the official configuration files and provide a just-works effect, otherwise one needs to manually run the defined scripts in package.json. 
IntelliJ for example automatically picks of the linter configuration if it's found.
